apiVersion: v1
kind: Pod
metadata:
  name: greedy-pod
  namespace: marketing-demo
spec:
  containers:
  - name: crypto-miner
    image: nginx:alpine
    resources:
      requests:
        cpu: "4" # Quota is 2
        memory: "8Gi" # Quota is 4Gi
      limits:
        cpu: "4"
        memory: "8Gi"
